### PR TITLE
feat: add rancher RKE2 support

### PR DESCRIPTION
**Pull request by flavio**
Enable installation on RKE2.

I would like to add this feature also to the Go rewrite, but I didn't understand how the distribution detection mechanism works.

### CODE REVIEW

**Comment by flavio** [comment]
It seems the failure is unrelated with my PR :(

**Comment by 0xE282B0** [comment]
Thanks for the PR @flavio, RKE2 support is great!
The go installer doesn't have K8s distribution detection yet, so you can't find it yet 😊.

The build pipeline issue is fixed. Could you please rebase your commit?
What do you consider the easiest way to set up and test an RKE2 cluster?

**Comment by flavio** [comment]
@0xE282B0 I've rebased :)

Thanks for the explanation about the go-rewrite branch

**Comment by 0xE282B0** [comment]
Thank you @flavio, LGTM!

**Pull request merged**
